version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: "database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=unit2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - fullstack
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: "unit2"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "root"
      DB_DB: "unit2"
      DB_HOST: "db"
      DB_PORT: "5432"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  pgdata:

networks:
  fullstack:
    driver: bridge